# Generated by Django 3.0.1 on 2020-01-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0002_auto_20200109_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'cisco_ios'), (2, 'cisco_nxos_ssh'), (3, 'cisco_s300'), (4, 'cisco_tp_tcce')]),
        ),
    ]
