# Generated by Django 3.0.1 on 2020-01-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0003_auto_20200109_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('users_name', models.CharField(max_length=50)),
                ('state_type', models.PositiveSmallIntegerField(choices=[(1, 'doha')])),
                ('city_type', models.PositiveSmallIntegerField(choices=[(1, 'Abu Hamour'), (2, 'Ain Khaled'), (3, 'Bu Samra'), (4, 'Al Dafna'), (5, 'Fereej Bin Mahmoud'), (6, 'Freej Al Murra'), (7, 'Al Gharrafa'), (8, 'Al Hilal'), (9, 'Al Jeryan'), (10, 'Al Khor')])),
            ],
        ),
    ]
