# Generated by Django 3.0.1 on 2020-01-11 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0004_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examples.Customer')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examples.Device')),
            ],
        ),
    ]
