# Generated by Django 3.0.1 on 2020-01-11 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0005_customer_device'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer_Device',
            new_name='CustomerDevice',
        ),
    ]
