#!/usr/bin/env python
from __future__ import print_function, unicode_literals

# Netmiko is the same as ConnectHandler
from netmiko import Netmiko
from getpass import getpass

net_connect = Netmiko(
    host="XXXX",
    username="XXX",
    password="XXX",
    device_type="cisco_ios",
)

print(net_connect.find_prompt())
command1 = "show ip int brief"
command2 = "show version | include uptime"
output = net_connect.send_command(command2)
print(output)
output = net_connect.send_command(command1)
print(output)
net_connect.disconnect()
